//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long Id { get; set; }
        public string EmployeeId { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<long> DesignationId { get; set; }
        public string Education { get; set; }
        public string Responsibility { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string OperatingUnit { get; set; }
        public Nullable<long> OperatingUnitId { get; set; }
        public string Product { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Department { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public string Section { get; set; }
        public Nullable<long> SectionId { get; set; }
        public string SubSection { get; set; }
        public Nullable<long> SubSectionId { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    }
}
