//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CheckItems_GBW
    {
        public string T_WO { get; set; }
        public string T_CK_BT { get; set; }
        public string T_CK_FT { get; set; }
        public string T_CK_AT { get; set; }
        public string T_CK_SMTMMI { get; set; }
        public string T_CK_MMI { get; set; }
        public string T_CK_SWV { get; set; }
        public string T_CK_SWBuilTime { get; set; }
        public string T_CK_IMEIW { get; set; }
        public string T_CK_Reset { get; set; }
        public string T_CK_IMEIC { get; set; }
        public string T_CK_Battery { get; set; }
        public string T_CK_Charger { get; set; }
        public string T_CK_GiftBox { get; set; }
        public string T_CK_RelationCheck { get; set; }
        public string T_CK_GiftBoxW { get; set; }
        public string T_CK_CartonBox { get; set; }
        public string T_CK_CartonBoxCheck { get; set; }
        public string T_CK_CartonBoxW { get; set; }
        public string T_CK_Pallet { get; set; }
        public string T_CK_PalletCheck { get; set; }
        public string T_CK_IMEI { get; set; }
        public string T_CK_IRIS { get; set; }
        public string T_CK_Tee { get; set; }
        public string T_CK_IMEIC2 { get; set; }
        public string T_CK_GoogleKey { get; set; }
    }
}
