//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Project_R5
    {
        public string T_WOID { get; set; }
        public string T_IMEI1 { get; set; }
        public string T_IMEI2 { get; set; }
        public string T_IMEI3 { get; set; }
        public string T_IMEI4 { get; set; }
        public string T_SN { get; set; }
        public string T_Barcode { get; set; }
        public string T_BT { get; set; }
        public string T_WIFI { get; set; }
        public string T_SWV { get; set; }
        public string T_BatterySN { get; set; }
        public Nullable<System.DateTime> T_ConnectBattery_Time { get; set; }
        public string T_ChargerSN { get; set; }
        public Nullable<System.DateTime> T_ConnectCharger_Time { get; set; }
        public string T_WriteIMEI_Flag { get; set; }
        public Nullable<System.DateTime> T_WriteIMEI_Time { get; set; }
        public string T_CheckIMEI_Flag { get; set; }
        public Nullable<System.DateTime> T_CheckIMEI_Time { get; set; }
        public string T_ResetFactory_Flag { get; set; }
        public Nullable<System.DateTime> T_ResetFactory_Time { get; set; }
        public string T_GiftPrint_Flag { get; set; }
        public Nullable<System.DateTime> T_GiftPrint_Time { get; set; }
        public string T_RelationCheck_Flag { get; set; }
        public Nullable<System.DateTime> T_RelationCheck_Time { get; set; }
        public Nullable<double> T_GiftWeight { get; set; }
        public Nullable<System.DateTime> T_GiftWeight_Time { get; set; }
        public string T_BOXID { get; set; }
        public Nullable<System.DateTime> T_BOXID_Time { get; set; }
        public Nullable<double> T_BoxWeight { get; set; }
        public Nullable<System.DateTime> T_BoxWeight_Time { get; set; }
        public string T_BOXGiftCheck_Flag { get; set; }
        public Nullable<System.DateTime> T_BOXGiftCheck_Time { get; set; }
        public string T_PalletID { get; set; }
        public Nullable<System.DateTime> T_PalletID_Time { get; set; }
        public string T_ExportFlag { get; set; }
        public Nullable<System.DateTime> T_Export_Time { get; set; }
        public string T_BatchIndn { get; set; }
        public string T_SPC1 { get; set; }
        public string T_SPC2 { get; set; }
        public string T_SPC3 { get; set; }
        public string T_OutPalletNo { get; set; }
        public Nullable<System.DateTime> T_OutPalletNo_Time { get; set; }
        public Nullable<int> T_Vol { get; set; }
        public string T_ReadIMEIPrint_Flag { get; set; }
        public Nullable<System.DateTime> T_ReadIMEIPrint_Time { get; set; }
        public string T_SubSN { get; set; }
        public string T_WriteIMEI_Man { get; set; }
        public string T_CheckIMEI_Man { get; set; }
        public string T_GiftPrint_Man { get; set; }
        public string T_RelationCheck_Man { get; set; }
        public string T_GiftWeight_Man { get; set; }
        public string T_BoxWeight_Man { get; set; }
        public string T_CheckIMEI_Flag2 { get; set; }
        public Nullable<System.DateTime> T_CheckIMEI_Time2 { get; set; }
    }
}
