//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_ReworkCharger
    {
        public long T_ID { get; set; }
        public string T_WOID { get; set; }
        public string T_IMEI1 { get; set; }
        public string T_OldChargerSN { get; set; }
        public string T_NewChargerSN { get; set; }
        public Nullable<System.DateTime> T_Datetime { get; set; }
        public string T_Project { get; set; }
    }
}
