//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_WOManagement
    {
        public string T_WO { get; set; }
        public string T_PO { get; set; }
        public string T_Project { get; set; }
        public string T_Model { get; set; }
        public string T_Color { get; set; }
        public string T_EANCode { get; set; }
        public string T_RefNo { get; set; }
        public string T_MRP { get; set; }
        public string T_SWVersion { get; set; }
        public string T_HWVersion { get; set; }
        public string T_FactoryCode { get; set; }
        public string T_Country { get; set; }
        public Nullable<int> T_TotalCount { get; set; }
        public Nullable<int> T_AllocateCount { get; set; }
        public string T_DualIMEI { get; set; }
        public string T_BeginIMEI { get; set; }
        public string T_CurrentIMEI { get; set; }
        public string T_EndIMEI { get; set; }
        public string T_HaveSN { get; set; }
        public string T_BeginSN { get; set; }
        public string T_CurrentSN { get; set; }
        public string T_EndSN { get; set; }
        public Nullable<int> T_SNFlowLen { get; set; }
        public string T_WriteWiFi { get; set; }
        public string T_BeginWiFiMac { get; set; }
        public string T_CurrentWiFiMac { get; set; }
        public string T_EndWiFiMac { get; set; }
        public string T_WriteBT { get; set; }
        public string T_BeginBTMac { get; set; }
        public string T_CurrentBTMac { get; set; }
        public string T_EndBTMac { get; set; }
        public Nullable<double> T_MinGiftBoxW { get; set; }
        public Nullable<double> T_MaxGiftBoxW { get; set; }
        public string T_CartonNoFormat { get; set; }
        public Nullable<int> T_CartonBoxCap { get; set; }
        public Nullable<double> T_MinCartonBoxW { get; set; }
        public Nullable<double> T_MaxCartonBoxW { get; set; }
        public Nullable<int> T_PalletCap { get; set; }
        public string T_PalletNoFormat { get; set; }
        public string T_BeginPallID { get; set; }
        public string T_EndPallID { get; set; }
        public string T_IMEILableFormatDate { get; set; }
        public string T_GiftBoxLableFormatDate { get; set; }
        public string T_CartonBoxLableFormatDate { get; set; }
        public string T_PalletLableFormatDate { get; set; }
        public Nullable<System.DateTime> T_BuildDateTime { get; set; }
        public string T_BuildIPAddr { get; set; }
        public Nullable<System.DateTime> T_ModifyDateTime { get; set; }
        public string T_ModifyIPAddr { get; set; }
        public string T_Close { get; set; }
        public string T_BatteryCheckCode { get; set; }
        public string T_ChargerCheckCode { get; set; }
        public string T_2DCode { get; set; }
        public string T_2DCode_IMEI1 { get; set; }
        public string T_2DCode_IMEI2 { get; set; }
        public string T_2DCode_SN { get; set; }
        public string T_2DCode_SEP { get; set; }
        public string T_SAPCode { get; set; }
        public string T_OutPalletNoFormat { get; set; }
        public string T_OutPalletLableFormatDate { get; set; }
        public string T_SNFormat { get; set; }
        public Nullable<int> T_OutPalletCap { get; set; }
        public string T_CheckVol { get; set; }
        public Nullable<double> T_MinVol { get; set; }
        public Nullable<double> T_MaxVol { get; set; }
        public string T_Confirm { get; set; }
        public string T_MSN { get; set; }
        public string T_CSWVersion { get; set; }
        public string T_PartNo { get; set; }
        public string T_part { get; set; }
        public string T_SameIMEI { get; set; }
        public string T_BeginBoxID { get; set; }
        public string T_EndBoxID { get; set; }
        public string T_BeginOutPallID { get; set; }
        public string T_EndOutPallID { get; set; }
        public string T_HaveSubSN { get; set; }
        public string T_BeginSubSN { get; set; }
        public string T_CurrentSubSN { get; set; }
        public string T_EndSubSN { get; set; }
        public Nullable<int> T_SubSNFlowLen { get; set; }
        public string T_2DCode_SubSN { get; set; }
        public string T_SubSNFormat { get; set; }
        public Nullable<double> T_MinQuantity { get; set; }
        public Nullable<double> T_MaxQuantity { get; set; }
    }
}
