//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issues
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string FaultType { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
