//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaster
    {
        public long ProductionId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<long> LineId { get; set; }
        public Nullable<long> PackagingLineId { get; set; }
        public string MobileCode { get; set; }
        public string Imei1 { get; set; }
        public string Imei2 { get; set; }
        public string Passed { get; set; }
        public string QcStation { get; set; }
        public string AgingBatchNumber { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FinallyPassed { get; set; }
        public Nullable<System.DateTime> FinallyPassedTime { get; set; }
        public Nullable<long> FinallyPassedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> FunctionalBy { get; set; }
        public Nullable<System.DateTime> FunctionalAD { get; set; }
        public Nullable<long> AestheticBy { get; set; }
        public Nullable<System.DateTime> AestheticAD { get; set; }
        public Nullable<long> AgingBy { get; set; }
        public Nullable<System.DateTime> AgingAD { get; set; }
        public Nullable<long> PackagingBy { get; set; }
        public Nullable<System.DateTime> PackagingAD { get; set; }
        public Nullable<long> PackagingAstheticBy { get; set; }
        public Nullable<System.DateTime> PackagingAstheticAD { get; set; }
        public Nullable<long> PackagingOQCBy { get; set; }
        public Nullable<System.DateTime> PackagingOQCAD { get; set; }
        public string OQCBatchNumber { get; set; }
    }
}
