//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectBomList
    {
        public long Id { get; set; }
        public long ProjectMasterId { get; set; }
        public string ProjectName { get; set; }
        public long ComponentId { get; set; }
        public string ComponentName { get; set; }
        public string ComponentNumber { get; set; }
        public string IcVendor { get; set; }
        public int Quantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
