//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssemblyLineSetup
    {
        public int Id { get; set; }
        public Nullable<int> AssemblyLineId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> IssuedQuantity { get; set; }
        public Nullable<int> HourlyTargetQuantity { get; set; }
        public Nullable<int> TotalTargetQuantity { get; set; }
        public Nullable<int> ManPower { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> PreviousQuantity { get; set; }
    }
}
