//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatteryComponentInfo
    {
        public long Id { get; set; }
        public Nullable<long> PorjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> LineId { get; set; }
        public string LineName { get; set; }
        public Nullable<int> PcbIssued { get; set; }
        public Nullable<int> PcbPassed { get; set; }
        public Nullable<int> PcbFailed { get; set; }
        public Nullable<int> CellIssued { get; set; }
        public Nullable<int> CellPassed { get; set; }
        public Nullable<int> CellFailed { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
