//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComponentRequisition
    {
        public long Id { get; set; }
        public Nullable<long> ComponentId { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> ReqQuantity { get; set; }
        public string OracleReqNumber { get; set; }
        public Nullable<System.DateTime> OracleReqDate { get; set; }
        public Nullable<int> UsedQuantity { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
