//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeletdPackagingBatchData
    {
        public int Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> LineId { get; set; }
        public string MobileCode { get; set; }
        public string Imei1 { get; set; }
        public string Imei2 { get; set; }
        public string Sample { get; set; }
        public string SystemBatch { get; set; }
        public string MasterBatch { get; set; }
        public string Passed { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    }
}
