//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> RoleId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> LineId { get; set; }
        public string RoleName { get; set; }
        public string LineName { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string Shifting { get; set; }
    
        public virtual tblRoles tblRoles { get; set; }
    }
}
