//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoles
    {
        public tblRoles()
        {
            this.tblLogin = new HashSet<tblLogin>();
        }
    
        public long Id { get; set; }
        public string Roles { get; set; }
    
        public virtual ICollection<tblLogin> tblLogin { get; set; }
        public virtual tblRoles tblRoles1 { get; set; }
        public virtual tblRoles tblRoles2 { get; set; }
    }
}
