//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRework
    {
        public long ReworkId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> LineId { get; set; }
        public string MobileCode { get; set; }
        public string Imei1 { get; set; }
        public string Imei2 { get; set; }
        public string Issues { get; set; }
        public string FailedStation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> StartedBy { get; set; }
        public Nullable<System.DateTime> PauseDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<long> FinishedBy { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ProjectName { get; set; }
    }
}
