//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCMS_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSolderingOthers
    {
        public int Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> ComponentId { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> RequsitionQuantity { get; set; }
        public Nullable<int> UsedQuantity { get; set; }
        public Nullable<int> WastedQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> ReworkId { get; set; }
    }
}
